remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'logger-fp-ts on GitHub':
    - 'https://github.com/thewilkybarkid/logger-fp-ts'